server:
  port: 8083

spring:
  application:
    name: booking-service
  r2dbc:
    url: r2dbc:h2:file:./db/booking_db;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password: password
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
